# Generated by Django 5.0.6 on 2024-07-19 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_rename_name_categoria_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
    ]
